# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('uses_electricity', models.BooleanField(default=False)),
                ('uses_water', models.BooleanField(default=False)),
                ('uses_gas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dwelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Dwelling')),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expenses.Room'),
        ),
    ]
