# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watts', models.IntegerField()),
                ('time_minutes', models.IntegerField()),
                ('occurences_per_week', models.IntegerField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Appliance')),
            ],
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres', models.IntegerField()),
                ('occurences_per_week', models.IntegerField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Appliance')),
            ],
        ),
    ]
