# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20170830_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterusage',
            old_name='occurences_per_week',
            new_name='occurrences_per_week',
        ),
    ]
